name: Node CI

on:
  push:
    paths:
      - 'back/**'
  pull_request:
    paths:
      - 'back/**'

jobs:
  build:

    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: "Install"
        working-directory: ./back
        run: npm install
      - name: "Build"
        working-directory: ./back
        run: npm run build --if-present
      - name: "Test"
        working-directory: ./back
        run: npm test